### ISSUE TITLE
loginWithAppServiceMSI throws "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by sschmeck** [Azure/ms-rest-nodeauth#114]
**Package Version**: `3.0.6`
- [x] **nodejs**
   - **nodejs version**: `v12.18.0`
   - **os name/version**: `Windows`/Azure Function Runtime version `3.0.15371.0`

**Describe the bug**

When you call a Azure HTTP Trigger Function with more than 100 concurrent requests, the functions `loginWithAppServiceMSI()`/`getToken()` return `Unexpected end of JSON input` for some requests.

```TypeScript
import * as msRestNodeAuth from '@azure/ms-rest-nodeauth';
// ...
async function getNewAccessToken(): Promise<string> {
  try {
    const credentials = await msRestNodeAuth.loginWithAppServiceMSI({
      resource: process.env.APPLICATION_ID
    });
    return (await credentials.getToken()).accessToken;
  } catch (error) {
    // catches  'Unexpected end of JSON input'
    throw new Error(`Retrieving Managed Service Identity (MSI) token failed with '${error.message}'.`);
  }
}
```

**To Reproduce**

1. Create an Azure Function App (Consumption plan) with an HTTP Trigger
2. Use the `@azure/ms-rest-nodeauth` as described above
3. Send more than 100 concurrent requests to the HTTP Trigger endpoint

**Expected behavior**
More expressive error message or more sensible token retrieval. 

**Additional context**
The error is thrown while executing [`parseTokenResponse()`](https://github.com/Azure/ms-rest-nodeauth/blob/2ece38f40efeb50a4e2dd5dd887bab386cf808f4/lib/credentials/msiAppServiceTokenCredentials.ts#L109).

During the error analysis, it turned out, that the underlying `IDENTITY_ENDPOINT` returns `429` status codes under load. It seems, the current error handling doesn't handle that kind of response appropriately.

**Comment by sadasant** [comment]
Hello @sschmeck , I hope this comment finds you well.

I wanted to let you know that, even though it will take me some time to provide an answer, I will indeed provide an answer within the next 24 hours. Thank you so much for posting this issue!

**Comment by sadasant** [comment]
@sschmeck I've been investigating this. My setup should be ok to reproduce this at this point. Perhaps unsurprisingly, HTTP status code 429 means "too many requests". I'll catch up with my team to see what is reasonable to do so in that case.

**Comment by sadasant** [comment]
@sschmeck 

It just came to me to mention the expiration date of these tokens. These tokens usually last about a day, I believe. Have you checked the expiration date of the token that results of the `getToken` call? Would you be able to cache the token?

Since this is Azure Function, hosting this token in memory might not help, but you can use temporary files or something like redis to store the token.

Does that help? How does that sound?

**Comment by sschmeck** [comment]
@sadasant, thanks for your reply.

I replaced `@azure/ms-rest-nodeauth` by REST calls using `axios` as described in [Using the REST protocol](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity#using-the-rest-protocol) and added a local cache, which fixed the issue to me.

The error message mentioned above is misleading. Do you think, the current [error handling](https://github.com/Azure/ms-rest-nodeauth/blob/2ece38f40efeb50a4e2dd5dd887bab386cf808f4/lib/credentials/msiAppServiceTokenCredentials.ts#L105) could be improved (e.g. throw to `Too many requests` instead of `Unexpected end of JSON input`)?

In addition, does it make sense to implement some local caching within `@azure/ms-rest-nodeauth`?

**Comment by sadasant** [comment]
Hello @sschmeck !

I am not sure if that suggestion makes sense in that line of code, since it might not be where the root of the problem is. This `bodyAsText` comes straight from the server: https://github.com/Azure/ms-rest-js/blob/4208098ab146ad6d37611306c01aac3c93db0941/lib/xhrHttpClient.ts#L110

I need more time to test this to see what fix makes the most sense.

Also, in regards to the local caching inside of `@azure/ms-rest-nodeauth`, we're currently trying to avoid doing further changes to this library. Our time is mostly invested on improving `@azure/identity`, which will eventually fully deprecate `@azure/ms-rest-nodeauth`.

Having said that, please let us know if we can be useful in any other way!

**Comment by sschmeck** [comment]
I close the issue. It seems, that I can use `@azure/identity` for getting the Managed Identity token instead, which provides a better error handling. I wasn't aware of that option. :)
