### ISSUE TITLE
Two Different Tenant Id Requirements

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/ms-rest-nodeauth#132]
**Is your feature request related to a problem? Please describe.**
I am validating our Keyvault Azure Stack SDK samples against the new 2020-09-01-hybrid profile for JavaScript SDK and realized it doesn’t work due to the following error:

```
(node:28536) UnhandledPromiseRejectionWarning: Error: parameters.properties.tenantId with value "adfs" must be of type string and a valid uuid.
```

First, this is the request sender used for keyVaultClient.vaults.createOrUpdate:
https://github.com/Azure/ms-rest-azure-js/blob/a9cee4480a8710d5c81890ae7cb7a1dea559ec65/lib/azureServiceClient.ts#L69
Eventually the above code calls the following:
https://github.com/Azure/ms-rest-js/blob/de6aa5157603639001785b4a43afa5f325381dbd/lib/serializer.ts#L325

For the current azure stack ADAL login, ms-rest-nodeauth forces users to pass the ADFS tenant Id as "adfs" string when doing login:
https://github.com/Azure/ms-rest-nodeauth/blob/master/lib/msRestNodeAuth.ts#L42

But this will throw error in the above ms-rest -js check because “adfs” is not a UUID. Basically ms-rest-nodeauth wants to use “adfs”, and ms-rest -js doesn’t like it since it is not a UUID. The other modules do not have this issue since I assume they did not need to serialize the tenant Id. The work-around is to replace “tenantId” with the actual UUID because an ADFS environment still has a tenant Id.

So this raises the question why are we forcing “adfs” string in place of the UUID? It is a user-experience issue to have the user use both “adfs” and the UUID as the tenant Id depending on what function they are calling. Ideally, only UUID should be passed, so the question is why are we forcing “adfs” string on user login?

Sample branch for repro: https://github.com/Azure-Samples/hybrid-keyvault-nodejs-create-secret/tree/update-api-version

**Describe the solution you'd like**
A single value, the tenant UUID, being used for tenant Ids.

**Describe alternatives you've considered**
Alternative solution is to use "adfs" as tenant Id for login, and the tenant UUID for function calls that require serialization. But this is a user-experience issue since the user should not be aware of what parameters and methods end up using serialization so that they know whether to pass "adfs" or the tenant UUID. Even if there is documentation stating when to pass "adfs" or tenant UUID, this is not good user-experience.

**Additional context**
This is reproduced in 2020-09-01-hybrid JavaScript SDK profile for Azure Stack Hub. I do not know the reason why "adfs" and tenant UUID is used for tenant Id at the same time, but maybe there is a good reason for it that I am not aware of?

**Comment by sadasant** [comment]
Hello, Wei! I have an update.

Your debugging is correct! Specifying `adfs` as the `tenantId` will trigger an error at this point [ms-rest-js/lib/serializer.ts#L325](https://github.com/Azure/ms-rest-js/blob/de6aa5157603639001785b4a43afa5f325381dbd/lib/serializer.ts#L325). In this case, this error is expected because the swagger of the Key Vault service specifies that this `tenantId` property has to be of the type `uuid`. You can see one reference in one of such references in one of the latest swagger files for the Key Vault resource manager: [resource-manager/Microsoft.KeyVault/preview/2020-04-01-preview/keyvault.json#L1078-L1082](https://github.com/Azure/azure-rest-api-specs/blob/c234651f2885c07ff4a77e50c883145949fda5fa/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2020-04-01-preview/keyvault.json#L1078-L1082). ms-rest-js is doing what it should be doing: It’s only allowing UUIDs to be sent as the value of this specific field.

Since the Azure Key Vault service team is responsible for writing the specifications of their services, I’ve routed your request to the service team through this issue: https://github.com/Azure/azure-rest-api-specs/issues/15108

Thank you for bringing this problem to us! Through your feedback, we’ll be able to improve our SDKs.

**Comment by sadasant** [comment]
@TheOnlyWei 

Keep in mind that, once the specifications are updated, we will need to re-generate and release new @azure/arm-keyvault-* clients.

**Comment by TheOnlyWei** [comment]
@sadasant I believe the UUID enforicement for keyvault API makes sense. I just don't understand why we are passing "adfs" as tenant Id for the login. Who do we contact to request a feature to allow tenant UUID for the login in an ADFS Azure Stack environment?

Link for login sample:
https://github.com/Azure-Samples/hybrid-keyvault-nodejs-create-secret/blob/5c6160a5ecb42198efc5b7ece929a3418192eb7f/index.js#L103

**Comment by sadasant** [comment]
@TheOnlyWei since this issue is really a service request, as discussed here: https://github.com/Azure/azure-rest-api-specs/issues/15108#issuecomment-922097802

Can we close this issue on the ms-rest-nodeauth repository?

**Comment by sadasant** [comment]
Given that this is a service request, and that the service team has answered here: https://github.com/Azure/azure-rest-api-specs/issues/15108#issuecomment-922097802 I’ll close this issue for now. Thank you for your time invested in our libraries! Please let us know if there’s anything else we can help you with.
