### ISSUE TITLE
Port over auth related changes done in ms-rest-azure

### ISSUE THREAD

**Issue by amarzavery** [Azure/ms-rest-nodeauth#5]
Commit history of ms-rest-azure https://github.com/Azure/azure-sdk-for-node/commits/master/runtime/ms-rest-azure/lib.

I would recommend taking a look at changes made in ms-rest-azure from September 11, 2017 commit.

**Comment by alexeldeib** [comment]
@amarzavery I took a look at opening up token audience since it is blocking for me. I was able to successfully acquire a token with tokenAudience = https://api.applicationinsights.io using this diff. I tried to stick fairly close to the corresponding code in ms-rest-azure, and otherwise add as little else as possible. Let me know if you think this is worth a PR to run with?

https://github.com/Azure/ms-rest-nodeauth/compare/master...alexeldeib:master

**Comment by alexeldeib** [comment]
Mostly follows this commit https://github.com/Azure/azure-sdk-for-node/commit/126ee8b3aebadd00fd904da3478167fb71ee738c#diff-312a751ba50d2de2472f78dd7d9a5d8f

**Comment by amarzavery** [comment]
@alexeldeib - The changes look good. One comment. I am not in the favor of maintaining another static array `ManagementPlaneTokenAudiences`. All those urls are coming from the activeDirectoryResourceId of the environment. Hence looking for that property in the environment should be good enough. What do you think?

**Comment by amarzavery** [comment]
@kpajdzik - Please take a look at this issue.

**Comment by alexeldeib** [comment]
@amarzavery Opened https://github.com/Azure/ms-rest-nodeauth/pull/8 

Diff for activeDirectoryResourceId:https://github.com/Azure/ms-rest-nodeauth/pull/8/commits/6153d3a87079e665b36dfbf61f0691e4dfc597f8
